### ISSUE TITLE
error: property 'resetValue' not found on object of type 'TTCounterLabel *'

### ISSUE THREAD

**Issue by orchestor** [EvgenyKarkan/TrackMyTime#35]
/Users/grant/project/TrackMyTime/TrackMyTime/TrackMyTime/Classes/Controllers/EKTimeTrackViewController.m:232:41: error: property 'resetValue' not found on object of type 'TTCounterLabel *'
        self.timeTrackView.counterLabel.resetValue = 0;

I can not compile the App, could you give some pointers about this?

**Comment by EvgenyKarkan** [comment]
Hi @orchestor 
I'm running Xcode 7.3 (7D175), iOS 9.3 iPhone 6 Simulator and everything is OK.
Could you add more details?

**Comment by EvgenyKarkan** [comment]
Ok, I was able to reproduce. Will take a look..

**Comment by orchestor** [comment]
Xcode 7.3.1

Build version 7D1014



ProductName: Mac OS X

ProductVersion: 10.11.6

BuildVersion: 15G31


Simulator doesn't work.


I am upgrading the iOS. now

**Comment by EvgenyKarkan** [comment]
Ok, I've deleted cocoa pods stuff from the project and now all 3-rd party libs are directly inside project's folder, for me it is better as I want in future to be able to customise libs code to my needs.
Please try to pull changes from master branch, open Xcode project (no workspace anymore), than try to build and run.

**Comment by EvgenyKarkan** [comment]
Seems everything is OK, if you have no issues, please close the current issue. Thanks :)

**Comment by orchestor** [comment]
2016-08-01 16:53:26.200 run[48996:11947036] Crashlytics.framework/run 1.3.14

2016-08-01 16:53:26.252 run[48996:11947036]


Crashlytics: You must install Crashlytics to continue.
https://api.crashlytics.com/api/v1/4760756e56b00e661fdfca38443023c06fd79797/confirm/com.Lin.trackmytime


If this machine is a build server please remove Crashlytics.app if present
and use xcodebuild so that TrackMyTime.app.dSYM is uploaded.

Command /bin/sh failed with exit code 1


Seems I need install Crashlytics separately, is it right?

**Comment by EvgenyKarkan** [comment]
Hi @orchestor, sorry for not so quick response, I guess we are living in different time zones :)
Ok, I will handle Crashlytics and push code later today.

**Comment by EvgenyKarkan** [comment]
Ok, just pushed to master branch, please try again @orchestor.

**Comment by orchestor** [comment]
Solved the issue. Thanks.
